### PR TITLE
Make tests pass for GR and PyPlot 2 (fix #670 and #838)

### LINKED ISSUE #670: Make tests pass
The VRT tests fail because of the PyPlot.jl upgrade to Matplotlib 2.0.

### PR DESCRIPTION
**Pull request by daschw**
this is a clean copy of https://github.com/JuliaPlots/Plots.jl/pull/877.

Let's see if the tests still pass (trying all testexamples for both gr and pyplot) ...

### CODE REVIEW

**Comment by daschw** [comment]
Passing :smile:
Adding the pyplot animations increased the travis testing time from 8 min 44 sec to 10 min 31 sec. I think that's acceptable.

**Comment by mkborregaard** [comment]
agreed

**Comment by mkborregaard** [comment]
I think we're good to go :-)

**Comment by daschw** [comment]
should I close #670 and #838 with this?

**Comment by mkborregaard** [comment]
👍

**Comment by mkborregaard** [comment]
Now it'll be fun to see the status of the travis tests for the other pending PRs :-)

File: test/travis_commands.jl [hunk 1]
```diff
@@ -1,8 +1,8 @@
-# Pkg.clone("ImageMagick")
-# Pkg.build("ImageMagick")
+Pkg.clone("ImageMagick")
```
Comment (tkelman) [inline test/travis_commands.jl]: it'll be more representative of what users run with if you do Pkg.add and test against releases, instead of clone and master

Comment (mkborregaard) [inline test/travis_commands.jl]: Change for ImageMagick here: https://github.com/JuliaPlots/Plots.jl/pull/904
For GR, StatPlots and PlotUtils we sometimes have to develop in concert and time releases, so I'd like to keep as is.
