### PR TITLE
Fix `apng` extension versatility

### LINKED ISSUE #4316: Saving apng to .png file results in an error.
## Details

I am trying out the recently added APNG output.

I got an error when I save Animation using the apng function. The error occurs only if I give a filename with ".png" extension. It seems working if the extension is ".apng". I found code that checks the file extension to choose the appropriate ffmpeg line in animation.jl.

Are there any reasons to force .apng extension? I believe .png is also commonly used as the extension for Animated PNG. I appreciate if .png is also supported.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |x     |     |
pyplot       | x    |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots v1.31.7
GR v0.66.2
PyPlot v2.10.0

Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

### PR DESCRIPTION
**Pull request by curio-sitas**
Fix #4316 

We decided to use `png` extension for APNG files but i forgot to update these extension changes in the code during the last iteration before the pull request of the new feature. (ref #4295, #4293)

* **It is corrected now and tests are passing ✅**
* The code now outputs `.png` files by default and `.apng` if precised in the filename

We did not see this during tests because they dont check for file extensions.

## Example

```julia
using Plots

x = 1:0.1:30
y = sin.(x)
df = 2

anim = Plots.@animate for i = 1:df:length(x)
    plot(x[1:i], y[1:i], legend=false)
end

Plots.apng(anim, "tutorial_anim_fps30.png", fps = 30) # previously an error, now outputs a .png file

Plots.apng(anim, "tutorial_anim_fps30.apng", fps = 30) # previously correct, outputs a .apng file

Plots.apng(anim, fps = 30) # outputs a .png file when no filename is passed as argument
```

### CODE REVIEW

**Comment by curio-sitas** [comment]
@t-bltg

File: src/animation.jl [hunk 1]
```diff
@@ -123,7 +123,7 @@ function buildanimation(
                 `-v $verbose_level -framerate $framerate -i $(animdir)/%06d.png -i "$(animdir)/palette.bmp" -lavfi "paletteuse=dither=sierra2_4a" -loop $loop -y $fn`,
             )
         end
-    elseif file_extension(fn) == "apng"
+    elseif file_extension(fn) in ["png", "apng"]
```
Comment (t-bltg) [inline src/animation.jl:126]:
```suggestion
    elseif file_extension(fn) in ("png", "apng")
```

`Tuple`s are stack allocated, `Vector`s are heap allocated (hence less performant).

**Comment by curio-sitas** [comment]
Seems like the master branch is failing CI. The animation tests are passing though

**Comment by t-bltg** [comment]
I guess this is the effect of https://github.com/JuliaPlots/Plots.jl/issues/4304 (new `GR_jll`).

Can you run the `Plots` test suite, and upload the new reference images in a PR at https://github.com/JuliaPlots/PlotReferenceImages.jl ?

**Comment by curio-sitas** [comment]
> I guess this is the effect of #4304 (new `GR_jll`).
> 
> Can you run the `Plots` test suite (`pkg> test Plots`), and upload the new reference images in a PR at https://github.com/JuliaPlots/PlotReferenceImages.jl ?

I cannot commit because `test Plots` does not make any changes in `.julia\dev\PlotReferenceImages\`

**Comment by t-bltg** [comment]
I guess it's because you have an obsolete `GR_jll` installed ? Maybe you need to `pkg> update` ?

This should be the latest:
```julia
pkg> st -m GR_jll
Status `[...]/.julia/environments/v1.8/Manifest.toml`
  [d2c73de3] GR_jll v0.66.2+0
```

**Review by t-bltg — APPROVED** [review]
LGTM, thanks for fixing ci.
