### PR TITLE
fix error bars in log scale

### LINKED ISSUE #2961: [BUG] Disappearing errorbar under log scale
## Details
```
scatter([1:3], [0.1, 0.15, 0.08], yerror=[0.3, 0.1, 0.02], yscale=:log10, ylims=(10^-3,Inf))
```
image

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.6.3
Backend  version (`]st -m`): GR v0.52.0
Output of `versioninfo()`:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
```

### PR DESCRIPTION
**Pull request by Moelf**
fix #2961
before:
image
after:
image

### CODE REVIEW

File: src/recipes.jl [hunk 1]
```diff
@@ -1117,6 +1123,12 @@ end
         plotattributes[:y], plotattributes[:x], plotattributes[:z] =
             error_coords(yerr, y, x, z)
     end
+    for i in [:x, :y, :z]
+        _scale= Symbol(i, :scale)
+        if _scale ∈ keys(plotattributes) && plotattributes[_scale] == :log10
```
Comment (BeastyBlacksmith) [inline src/recipes.jl:1128]: This applies also for other log scales and likewise we'd need to consider the case of x-errors with log-scale

Comment (Moelf) [reply src/recipes.jl:1128]: `i` will iterate over `:x, :y, :z` and clamp each of their error bar in the same fashion, so this should be fine?

**Comment by mkborregaard** [comment]
I'm trying to understand why you have sub-zero error bars in log space in the first place?

**Comment by Moelf** [comment]
that's a valid question. because the statistical error for counting experiment is `log(N)`, if `N<1`, the symmetric error is greater than `N` itself. While it's un-physical, currently we can't have asymmetric error bar. And it's often not easy to derive what's "correct" value for the lower half, so this is still a good visual cue to say: don't read too much into this value since it's error bar is large.

File: src/recipes.jl (hunk 1 above)
Comment (BeastyBlacksmith) [reply src/recipes.jl:1128]: I am just saying that the `:xerror` recipe probably also needs this fix

**Review by daschw — APPROVED** [review]
