### PR TITLE
handle fractional and NaN epochs

### LINKED ISSUE #4248: [BUG]  `seriestype = :stepmid` can compute invalid values for `ticks=native` when using `DateTimes`
I am not sure if this is a bug in `PlotlyJS.jl` or `Plots.jl`, and I assume this is an edge case, but sometimes when using  `seriestype = :stepmid` with `ticks = :native` on a `DateTime` axis, the computed points of the `stepmid` may be invalid values.

(I might try to fix this myself, but I'd maybe need a hint for what direction to look into :wink:  )

## Details

```julia
# `t` that works (`Dates.Millisecond(10)` spacing):
t = Dates.now():Dates.Millisecond(10):(Dates.now()+Dates.Minute(1))

# `t` that doesn't work (`Dates.Millisecond(11)` spacing):
t = Dates.now():Dates.Millisecond(11):(Dates.now()+Dates.Minute(1))
y = rand(length(t))

plot(
	t, y,
	seriestype = :stepmid,
	ticks = :native,
)
```
yields
```
Failed to show value:

InexactError: Int64(6.37916595045745e13)

    Int64@float.jl:812[inlined]
    convert@number.jl:7[inlined]
    Millisecond@types.jl:61[inlined]
    UTM@types.jl:103[inlined]
    datetimeformatter@recipes.jl:7[inlined]
    #378@plotly.jl:535[inlined]
    iterate@generator.jl:47[inlined]
    collect_to!(::Vector{String}, ::Base.Generator{Vector{Float64}, Plots.var"#378#381"{typeof(RecipesPipeline.datetimeformatter)}}, ::Int64, ::Int64)@array.jl:782
    collect_to_with_first!@array.jl:760[inlined]
    _collect(::Vector{Float64}, ::Base.Generator{Vector{Float64}, Plots.var"#378#381"{typeof(RecipesPipeline.datetimeformatter)}}, ::Base.EltypeUnknown, ::Base.HasShape{1})@array.jl:754
    collect_similar@array.jl:653[inlined]
    map@abstractarray.jl:2867[inlined]
    plotly_convert_to_datetime(::Vector{Float64}, ::typeof(RecipesPipeline.datetimeformatter))@plotly.jl:535
    plotly_native_data(::Plots.Axis, ::Vector{Float64})@plotly.jl:526
    plotly_data(::Plots.Series, ::Symbol, ::Vector{Float64})@plotly.jl:506
    #384@none:0[inlined]
    iterate@generator.jl:47[inlined]
    indexed_iterate(::Base.Generator{Base.Iterators.Zip{Tuple{Tuple{Symbol, Symbol, Symbol}, Tuple{Vector{Float64}, Vector{Float64}, Nothing}}}, Plots.var"#384#387"{Plots.Series}}, ::Int64)@tuple.jl:92
    plotly_series(::Plots.Plot{Plots.PlotlyJSBackend}, ::Plots.Series)@plotly.jl:584
    #394@none:0[inlined]
    MappingRF@reduce.jl:95[inlined]
    _foldl_impl(::Base.MappingRF{Plots.var"#394#395"{Plots.Plot{Plots.PlotlyJSBackend}}, Base.BottomRF{typeof(vcat)}}, ::Base._InitialValue, ::Vector{Plots.Series})@reduce.jl:58
    foldl_impl@reduce.jl:48[inlined]
    mapfoldl_impl@reduce.jl:44[inlined]
    #mapfoldl#244@reduce.jl:162[inlined]
    mapfoldl@reduce.jl:162[inlined]
    #mapreduce#248@reduce.jl:289[inlined]
    mapreduce@reduce.jl:289[inlined]
    #reduce#250@reduce.jl:458[inlined]
    reduce@reduce.jl:458[inlined]
    plotly_series@plotly.jl:1040[inlined]
    plotly_series_json(::Plots.Plot{Plots.PlotlyJSBackend})@plotly.jl:1044
    js_body@plotly.jl:1109[inlined]
    plotly_html_body(::Plots.Plot{Plots.PlotlyJSBackend}, ::Nothing)@plotly.jl:1097
    plotly_html_body@plotly.jl:1071[inlined]
    html_body@plotlyjs.jl:38[inlined]
    embeddable_html@web.jl:26[inlined]
    _show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyJSBackend})@plotlyjs.jl:40
    show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyJSBackend})@output.jl:212
    show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:1124
    show_richest_withreturned(::IOContext{Base.DevNull}, ::Any)@PlutoRunner.jl:1046
    format_output_default(::Any, ::Any)@PlutoRunner.jl:954
    var"#format_output#50"(::IOContext{Base.DevNull}, ::typeof(Main.PlutoRunner.format_output), ::Any)@PlutoRunner.jl:971
    formatted_result_of(::Base.UUID, ::Base.UUID, ::Bool, ::Vector{String}, ::Nothing, ::Module)@PlutoRunner.jl:864
    top-level scope@none:1
```
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | x    |
pyplot       |     |     |x
plotlyjs     | x    |     |
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: `1.30.1`
Backend  version (`]st -m <backend(s)>`): `PlotlyJS v0.18.8`
Output of `versioninfo()`: 
```
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

### PR DESCRIPTION
**Pull request by MrHenning**
Note: This is my first PR for an OSS project, please forgive me if I missed and contributing guidelines...

fixes #4248

One can now use `ticks = :native` for `DateTime`s in combination with "fractional" Dates (e.g. from `bar()` and `seriestype = :step`.

```julia 
using Plots
using Dates
plotly()

x = [now() + Second(i) for i in 1:20]
y = rand(length(x))
plot(
    x, y,
    seriestype = :stepmid,
    ticks=:native,
)
scatter!(x,y)
```

Full plot:
plot_11

Zoomed in:
plot_12

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Hey, thank you for putting up this PR. I do wonder if we should add this fix to the `datetimeformatter` in general instead of fixing it for the plotly backend only.

The datetimeformatter lives [here](https://github.com/JuliaPlots/RecipesPipeline.jl/blob/master/src/recipes.jl).

**Comment by MrHenning** [comment]
Sounds like a good idea. I will give it a try!

File: src/backends/plotly.jl [hunk 1]
```diff
@@ -532,11 +532,11 @@ plotly_native_data(axis::Axis, a::Surface) = Surface(plotly_native_data(axis, a.
 
 function plotly_convert_to_datetime(x::AbstractArray, formatter::Function)
     if formatter == datetimeformatter
-        map(xi -> replace(formatter(xi), "T" => " "), x)
+        map(xi -> isfinite(xi) ? replace(formatter(xi), "T" => " ") : missing, x)
     elseif formatter == dateformatter
-        map(xi -> string(formatter(xi), " 00:00:00"), x)
+        map(xi -> isfinite(xi) ? replace(dateformatter(xi), "T" => " ") : missing, x)
```
Comment (BeastyBlacksmith) [inline src/backends/plotly.jl:537]:
```suggestion
        map(xi -> isfinite(xi) ? replace(formatter(xi), "T" => " ") : missing, x)
```

**Review by BeastyBlacksmith — COMMENTED** [review]
Also checkout #3503
