### PR TITLE
fix marker arguments (fix #1503 fix #1505)

### LINKED ISSUE #1503: Unable to use `scatter` with `plotlyjs` and `plotly` backends
```jl
using Plots
plotlyjs()

scatter([1], [2])
```
gives
```jl
UndefRefError: access to undefined reference

Stacktrace:
 [1] next(::Array{Dict{Symbol,Any},1}, ::Int64) at ./array.jl:548
 [2] _series_added(::Plots.Plot{Plots.PlotlyJSBackend}, ::Plots.Series) at /Users/dpsanders/.julia/v0.6/Plots/src/backends/plotlyjs.jl:57
 [3] _add_the_series(::Plots.Plot{Plots.PlotlyJSBackend}, ::Plots.Subplot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}) at /Users/dpsanders/.julia/v0.6/Plots/src/pipeline.jl:379
 [4] _process_seriesrecipe(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}) at /Users/dpsanders/.julia/v0.6/Plots/src/pipeline.jl:401
 [5] _plot!(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /Users/dpsanders/.julia/v0.6/Plots/src/plot.jl:235
 [6] #plot#208(::Array{Any,1}, ::Function, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at /Users/dpsanders/.julia/v0.6/Plots/src/plot.jl:58
 [7] (::RecipesBase.#kw##plot)(::Array{Any,1}, ::RecipesBase.#plot, ::Array{Int64,1}, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at ./<missing>:0
 [8] #scatter#676(::Array{Any,1}, ::Function, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at /Users/dpsanders/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381
 [9] scatter(::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at /Users/dpsanders/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381
 [10] include_string(::String, ::String) at ./loading.jl:522
```

Reported at https://discourse.julialang.org/t/cant-plot-one-point-with-plotly-after-running-pkg-update/10473 and on Slack.

https://github.com/sglyon/PlotlyJS.jl/issues/188

### LINKED ISSUE #1505: alpha no longer works
`scatter([1,2,3], alpha=0.1)` shows nearly-transparent points on 0.16.0, but full-color points on 0.17.0 (and master). Tested with `gr()`, in IJulia, Linux.

### PR DESCRIPTION
**Pull request by daschw**
#1467 Introduced some issues with marker arguments (cf. #1503, #1505). Thank you @dpsanders and @cstjean for reporting!

```julia
plotly() # or plotlyjs()
scatter([1], [2])
```
marker_plotly

```julia
gr()
scatter([1,2,3], alpha=0.1)
```
markeralpha_gr

Furthermore, other marker arguments should also work fine on GR, Plotly(JS), PyPlot and PGFPlots:
```julia
n = 20; x = 1:n
plot(
    scatter(x.^2, markeralpha = [0.8, 0.2], markercolor = [:orange, :red, :purple], markersize = [5, 8]),
    scatter(x.^2, markeralpha = linspace(1, 0, n), marker_z = sqrt.(x), markersize = 8),
    markerstrokewidth = 0,
    markershape = [:circle, :diamond, :dtriangle, :star5, :square]
    )
```
marker_arguments

### CODE REVIEW

File: src/utils.jl [hunk 1]
```diff
@@ -656,6 +660,31 @@ function get_fillalpha(series, i::Int = 1)
     _cycle(series[:fillalpha], i)
 end
 
+function get_markercolor(series, i::Int = 1)
+    mc = series[:markercolor]
+    mz = series[:marker_z]
+    if mz == nothing
+        isa(mc, ColorGradient) ? mc : _cycle(mc, i)
+    else
+        cmin, cmax = get_clims(series[:subplot])
```
Comment (mkborregaard) [inline src/utils.jl]: @daschw I can't tell exactly what you want here, but this implementation is very inefficient for big datasets, and is a cause of https://github.com/JuliaPlots/Plots.jl/issues/1682 
The reason is that e.g. in the spy example, we plot 1e6 points - then this function gets called for each individual point, which then again 1) calls `get_clims` that recalculates clims for all points of all series in the plot every time, and 2) generates and allocates a new `cgrad` for each new data point.
In the spy example (`n = 100_000; a = sprand(1:n, 1:n, ones(n)); p = spy(a); display(p)`, the `get_markercolor` function is responsible for 98% of all execution time according to the profiler. Almost all of that is spent in `ignorenan_extrema` recalculating the extrema again and again, so maybe a solution could simply be to calculate the clims once at the same time as xlims and ylims and storing them in `plotattributes`.

Comment (mkborregaard) [reply src/utils.jl]: To be specific, I'm talking about the version (which is not in Plots atm but shows the problem very well) where `:scatter` with `:marker_z` is used to show the matrix.

Comment (daschw) [reply src/utils.jl]: OK, I see, thanks for noticing!
I'd say we just add the methods
```julia
get_markercolor(series, cmin, cmax, i::Int = 1)
get_markercolor(series, clims, i::Int = 1)
```
and use them whenever the clims are already known.
