### PR TITLE
fix histograms with NaN; close #1212

### LINKED ISSUE #1212: histograms fail in the presence of NaNs
```julia
julia> a = randn(10);

julia> a[3] = NaN

julia> histogram(a)  #errors on the quantile call in in recipes.jl line 504
ERROR: ArgumentError: quantiles are undefined in presence of NaNs
Stacktrace:
 [1] #quantile!#546(::Bool, ::Function, ::Array{Float64,1}, ::Float64) at ./statistics.jl:688
 [2] (::Base.#kw##quantile!)(::Array{Any,1}, ::Base.#quantile!, ::Array{Float64,1}, ::Float64) at ./<missing>:0
 [3] #quantile#547(::Bool, ::Function, ::Array{Float64,1}, ::Float64) at ./statistics.jl:739
 [4] (::Plots.#_iqr#226)(::Array{Float64,1}) at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:504
 [5] #_auto_binning_nbins#224(::Symbol, ::Function, ::Tuple{Array{Float64,1}}, ::Int64) at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:528
 [6] (::Plots.#kw##_auto_binning_nbins)(::Array{Any,1}, ::Plots.#_auto_binning_nbins, ::Tuple{Array{Float64,1}}, ::Int64) at ./<missing>:0
 [7] map(::Plots.##230#231{Tuple{Array{Float64,1}},Symbol}, ::Tuple{Int64}) at ./tuple.jl:158
 [8] #_make_hist#232(::Bool, ::Void, ::Function, ::Tuple{Array{Float64,1}}, ::Symbol) at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:550
 [9] (::Plots.#kw##_make_hist)(::Array{Any,1}, ::Plots.#_make_hist, ::Tuple{Array{Float64,1}}, ::Symbol) at ./<missing>:0
 [10] macro expansion at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:566 [inlined]
 [11] apply_recipe(::Dict{Symbol,Any}, ::Type{Val{:barhist}}, ::UnitRange{Int64}, ::Array{Float64,1}, ::Void) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:287
 [12] _process_seriesrecipe(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}) at /Users/michael/.julia/v0.6/Plots/src/pipeline.jl:406
 [13] _process_seriesrecipe(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}) at /Users/michael/.julia/v0.6/Plots/src/pipeline.jl:415
 [14] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Float64,1}}) at /Users/michael/.julia/v0.6/Plots/src/plot.jl:231
 [15] (::RecipesBase.#kw##plot)(::Array{Any,1}, ::RecipesBase.#plot, ::Array{Float64,1}) at ./<missing>:0
 [16] #histogram#595(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381
 [17] histogram(::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381

julia> histogram(a, bins = :scott) # avoids the quantile call but fails in StatsBase
ERROR: InexactError()
Stacktrace:
 [1] trunc(::Type{Int64}, ::Float64) at ./float.jl:672
 [2] nbitslen(::Float64, ::Int64) at ./twiceprecision.jl:61
 [3] nbitslen at ./twiceprecision.jl:58 [inlined]
 [4] floatrange(::Float64, ::Float64, ::Float64, ::Float64) at ./twiceprecision.jl:119
 [5] histrange(::Float64, ::Float64, ::Int64, ::Symbol) at /Users/michael/.julia/v0.6/StatsBase/src/hist.jl:115
 [6] histrange(::Array{Float64,1}, ::Int64, ::Symbol) at /Users/michael/.julia/v0.6/StatsBase/src/hist.jl:54
 [7] _hist_edge(::Tuple{Array{Float64,1}}, ::Int64, ::Int64) at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:536
 [8] map(::Plots.##230#231{Tuple{Array{Float64,1}},Symbol}, ::Tuple{Int64}) at ./tuple.jl:158
 [9] #_make_hist#232(::Bool, ::Void, ::Function, ::Tuple{Array{Float64,1}}, ::Symbol) at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:550
 [10] (::Plots.#kw##_make_hist)(::Array{Any,1}, ::Plots.#_make_hist, ::Tuple{Array{Float64,1}}, ::Symbol) at ./<missing>:0
 [11] macro expansion at /Users/michael/.julia/v0.6/Plots/src/recipes.jl:566 [inlined]
 [12] apply_recipe(::Dict{Symbol,Any}, ::Type{Val{:barhist}}, ::UnitRange{Int64}, ::Array{Float64,1}, ::Void) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:287
 [13] _process_seriesrecipe(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}) at /Users/michael/.julia/v0.6/Plots/src/pipeline.jl:406
 [14] _process_seriesrecipe(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}) at /Users/michael/.julia/v0.6/Plots/src/pipeline.jl:415
 [15] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Float64,1}}) at /Users/michael/.julia/v0.6/Plots/src/plot.jl:231
 [16] (::RecipesBase.#kw##plot)(::Array{Any,1}, ::RecipesBase.#plot, ::Array{Float64,1}) at ./<missing>:0
 [17] #histogram#595(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:381
 [18] (::Plots.#kw##histogram)(::Array{Any,1}, ::Plots.#histogram, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at ./<missing>:0
```

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Not really I think - as we need the data to be in sync with keywords passed as vectors - e.g. marker_z if people use your scatterhist. I've added a much faster method for filternans in the 1-d case that uses `filter!`, I'm comfortable with that because that happens at the very end. With that, this vector:
```
a = randn(1*10^6)
a[rand(1:1*10^6, 5*10^4)] .= NaN
```
plots in 0.12 second, vs 0.9 seconds before this PR. 
But you're very welcome to suggest a faster implementation.

**Comment by mkborregaard** [comment]
hmm now I'm no longer sure about my keywords argument actually... Maybe we could just `filter!` early on, but where?

**Comment by oschulz** [comment]
> Maybe we could just filter! early on, but where?

Hm, we don't want to do this for all plots, just for histograms, so it can't be part of the generic data pre-processing. But maybe we can just call it once at the top of `_make_hist`, then `_auto_binning_nbins` etc. should get data that's already filtered, right?

**Comment by mkborregaard** [comment]
definitely not for all Plots, as `NaN`s are used in many plot types to separate series. I'll have a look at the top of _make_hist

**Comment by mkborregaard** [comment]
OK, I've pushed that change. Here are the timings
```julia
using BenchmarkTools, Plots
a = randn(10^6)
b = copy(a)
a[rand(1:10^6, 5*10^4)] .= NaN

# current master
julia> @btime histogram($b)
  80.986 ms (4951 allocations: 23.21 MiB)

julia> @btime histogram2d($b,$b)
  159.285 ms (3535 allocations: 46.20 MiB)

# this PR
julia> @btime histogram($b)
  95.434 ms (4972 allocations: 32.21 MiB)

julia> @btime histogram2d($b,$b)
  227.763 ms (3649 allocations: 82.21 MiB)

julia> @btime histogram($a)  #with NaNs makes no difference
  89.052 ms (4952 allocations: 31.47 MiB)
```
I can live with that.

File: src/recipes.jl [hunk 1]
```diff
@@ -589,9 +589,9 @@ Plots.@deps stepbins path
 wand_edges(x...) = (@warn("Load the StatPlots package in order to use :wand bins. Defaulting to :auto", once = true); :auto)
 
 function _auto_binning_nbins(vs::NTuple{N,AbstractVector}, dim::Integer; mode::Symbol = :auto) where N
-    _cl(x) = ceil(Int, NaNMath.max(x, one(x)))
+    _cl(x) = ceil(Int, max(x, one(x)))
```
Comment (mkborregaard) [inline src/recipes.jl]: given that we now know that there are no NaNs

File: src/recipes.jl [hunk 2]
```diff
@@ -635,7 +635,15 @@ _hist_edges(vs::NTuple{N,AbstractVector}, binning::Union{Integer, Symbol, Abstra
...
 
+_filternans(vs::NTuple{1,AbstractVector}) = filter!.(!isnan, vs)
+function _filternans(vs::NTuple{N,AbstractVector}) where N
+    _invertedindex(v, not) = [j for (i,j) in enumerate(v) if !(i ∈ not)]
+    nots = union(Set.(findall.(isnan, vs))...)
+    _invertedindex.(vs, Ref(nots))
+end
+
 function _make_hist(vs::NTuple{N,AbstractVector}, binning; normed = false, weights = nothing) where N
+    vs = _filternans(vs)
```
Comment (oschulz) [inline src/recipes.jl]: Re-binding `vs` may lead to trouble ... probably better to give either the filtered data or the function argument a different name.

Comment (oschulz) [reply src/recipes.jl]: It'll be hard to guarantee that the type won't change, right? In any case, I think it would be cleaner. And I vaguely remember I read somewhere that re-binding function arguments can lead to problems, but I have to admit I forgot when and why.

Comment (mkborregaard) [reply src/recipes.jl]: OK I'll do it and merge, doesn't really matter. But I'd think my _filternan function is guaranteed to return a Tuple{Vector{Float64}}. Thanks for taking a look!

**Comment by oschulz** [comment]
Nice!
