### PR TITLE
Check if any of the iterator args are zero

### LINKED ISSUE #1329: Plotting empty Shape gives DivideError
This happens under the Plotly backend too. Maybe the behavior could be a no-op, or maybe add an empty series, I'm not sure.

```
julia> plot(Shape([],[]))
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: DivideError: integer division error
Stacktrace:
 [1] fld at ./int.jl:191 [inlined]
 [2] mod at ./int.jl:171 [inlined]
 [3] mod1 at ./operators.jl:649 [inlined]
 [4] _cycle(::Array{Float64,1}, ::Int64)
```

### PR DESCRIPTION
**Pull request by wkearn**
Fixes #1329

### CODE REVIEW

File: src/utils.jl [hunk 1]
```diff
@@ -199,7 +199,7 @@ allnan(istart::Int, iend::Int, args::Tuple) = all(i -> anynan(i, args), istart:i
 
 function Base.start(itr::SegmentsIterator)
     nextidx = 1
-    if anynan(1, itr.args)
+    if !any(iszero,map(length,itr.args)) && anynan(1, itr.args)
```
Comment (daschw) [inline src/utils.jl]: `!any(isempty, itr.args)` would be clearer IMO.

Comment (wkearn) [reply src/utils.jl]: Good point!

**Comment by daschw** [comment]
Great, LGTM!
