### PR TITLE
Treat types without length as a single element

### LINKED ISSUE #2350: hline! after annotate! cannot re-draw plot with Date coordinate
```julia
        p = plot([Dates.Date(2019, 1, 1), Dates.Date(2019, 2, 1)], [3, 4])
        annotate!(p, [([Dates.Date(2019, 1, 15)], 3.2, Plots.text("Test", :red, :center))])
        hline!(p, [3.1])

ERROR: MethodError: no method matching length(::Date)
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:593
  length(::Base.MethodList) at reflection.jl:849
  length(::Core.MethodTable) at reflection.jl:923
  ...
Stacktrace:
 [1] process_annotation(::Plots.Subplot{Plots.PyPlotBackend}, ::Date, ::Float64, ::Plots.PlotText, ::Plots.Font) at /home/o01eg/.julia/packages/Plots/qZHsp/src/components.jl:594
 [2] process_annotation(::Plots.Subplot{Plots.PyPlotBackend}, ::Date, ::Float64, ::Plots.PlotText) at /home/o01eg/.julia/packages/Plots/qZHsp/src/components.jl:592
 [3] _update_subplot_periphery(::Plots.Subplot{Plots.PyPlotBackend}, ::Array{Any,1}) at /home/o01eg/.julia/packages/Plots/qZHsp/src/args.jl:1420
 [4] _update_subplot_args(::Plots.Plot{Plots.PyPlotBackend}, ::Plots.Subplot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Int64, ::Bool) at /home/o01eg/.julia/packages/Plots/qZHsp/src/args.jl:1523
 [5] _subplot_setup(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Array{Dict{Symbol,Any},1}) at /home/o01eg/.julia/packages/Plots/qZHsp/src/pipeline.jl:297
 [6] _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Float64,1}}) at /home/o01eg/.julia/packages/Plots/qZHsp/src/plot.jl:206
 [7] #plot!#143(::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:seriestype,),Tuple{Symbol}}}, ::typeof(plot!), ::Plots.Plot{Plots.PyPlotBackend}, ::Array{Float64,1}) at /home/o01eg/.julia/packages/Plots/qZHsp/src/plot.jl:158
 [8] (::RecipesBase.var"#kw##plot!")(::NamedTuple{(:seriestype,),Tuple{Symbol}}, ::typeof(plot!), ::Plots.Plot{Plots.PyPlotBackend}, ::Array{Float64,1}) at ./none:0
 [9] #hline!#428(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(hline!), ::Plots.Plot{Plots.PyPlotBackend}, ::Vararg{Any,N} where N) at /home/o01eg/.julia/packages/RecipesBase/zBoFG/src/RecipesBase.jl:370
 [10] hline!(::Plots.Plot{Plots.PyPlotBackend}, ::Vararg{Any,N} where N) at /home/o01eg/.julia/packages/RecipesBase/zBoFG/src/RecipesBase.jl:370
 [11] top-level scope at REPL[18]:1
```

Julia: 1.3.0
Versions:
```
  [336ed68f] CSV v0.5.21
  [a93c6f00] DataFrames v0.20.0
  [59287772] Formatting v0.4.1
  [708ec375] Gumbo v0.5.1
  [cd3eb016] HTTP v0.8.8
  [682c06a0] JSON v0.21.0
  [47be7bcc] ORCA v0.3.1
  [3b7a836e] PGFPlots v3.2.0
  [f0f68f2c] PlotlyJS v0.13.0
  [91a5bcdd] Plots v0.28.4
  [d330b81b] PyPlot v2.8.2
  [bd369af6] Tables v0.2.11
```

It looks like it uses `Base.length(::Number) = 1` so it works with number coordinates but Julia doesn't define such overloading for `Dates` types.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #2350
Workaround for types like Dates.Date which can be used for coordinates but doesn't have Base.length defined.

### CODE REVIEW

File: src/components.jl [hunk 1]
```diff
@@ -591,7 +591,17 @@ annotations(sa::SeriesAnnotations) = sa
 function process_annotation(sp::Subplot, xs, ys, labs, font = font())
     anns = []
     labs = makevec(labs)
-    for i in 1:max(length(xs), length(ys), length(labs))
+    xlength = if length(methods(length, (typeof(xs),))) == 0
```
Comment (mkborregaard) [inline src/components.jl]: Nice, thanks. Can you rewrite to use `? :` format for clarity?
