### PR TITLE
Tick formating fixes

### LINKED ISSUE #2810: [BUG] GR negative exponents look ugly
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     | x   |
plotly       |     |   x |
plotlyjs     |     |   x |
pgfplotsx    |     |  x  |
inspectdr    |     |     | x

Both
```
plot(1e-12 .* rand(100), ticks=:native)
plot(1e-12 .* rand(100))
```
produce (similar)

image
image

Note how the `-` negative sign is rendered uglily, whereas pyplot and other backends look normal.
I believe it is internal to GR, perhaps @jheinen  could help. The relevent code I belive is [here](https://github.com/JuliaPlots/Plots.jl/blob/07146e84e5e507f24cfc7d43375425494cb8bfa4/src/backends/gr.jl#L749)

### PR DESCRIPTION
**Pull request by yha**
Fixes scientific tick formatting in GRand plotly. 
Fix  #2810
Also fixes `formatter=:engineering` in GR.

### CODE REVIEW

**Comment by yha** [comment]
Not sure how to update the precompiles

File: src/utils.jl [hunk 1]
```diff
@@ -1050,8 +1050,8 @@ guidefont(ax::Axis) = font(
 )
 
 # ---------------------------------------------------------------
-# converts unicode scientific notation unsupported by pgfplots and gr
-# into a format that works
+# converts unicode scientific notation, as returned by Showoff,
+# to a tex-like format (supported by gr, pyplot, and gpfplot).
```
Comment (BeastyBlacksmith) [inline src/utils.jl:1054]:
```suggestion
# to a tex-like format (supported by gr, pyplot, and pgfplots).
```

**Comment by BeastyBlacksmith** [comment]
Can you post some before/ after pictures while I enable the precompile bot for all branches again?

**Comment by yha** [comment]
demos for
```
plot( plot([-1e10,1e10], yformatter=:engineering),
      plot([-1e-10,1e-10]),
      plot([0.001,1000], yscale=:log10) )
```
### GR
before:
gr-before
after:
gr-after
### Plotly
before:
plotly-before
after:
plotly-after
### PyPlot
before/after (no change):
pyplot-before

**Comment by yha** [comment]
Not sure why the change in ticks messes up the layout in plotly. Seems this extra space happens even with native ticks: `plot([-1e6,1e6], ticks=:native)` get a much bigger left margin than `plot([-1,1], ticks=:native)`

**Comment by yha** [comment]
What needs to be done to trigger SnoopCompile on this branch?

**Comment by isentropic** [comment]
Would you please explain why did Plotly got affected in the first place? I thought the changes are meant to be GR exclusive?
Other backends seemed to handle `-` sign just fine

File: src/backends/pyplot.jl [hunk 2]
```diff
@@ -176,15 +176,7 @@ function add_pyfixedformatter(cbar, vals::AVec)
...
 
 function labelfunc(scale::Symbol, backend::PyPlotBackend)
-    if scale == :log10
-        x -> PyPlot.LaTeXStrings.latexstring("10^{$x}")
-    elseif scale == :log2
-        x -> PyPlot.LaTeXStrings.latexstring("2^{$x}")
-    elseif scale == :ln
-        x -> PyPlot.LaTeXStrings.latexstring("e^{$x}")
-    else
-        x -> PyPlot.LaTeXStrings.latexstring(convert_sci_unicode(x))
```
Comment (isentropic) [inline src/backends/pyplot.jl:186]: I wonder if this else statement is still triggered?

Comment (isentropic) [reply src/backends/pyplot.jl:186]: It is pretty important as it fixed `Serif` fonts for pyplot

File: src/backends/pyplot.jl [hunk 3]
```diff
@@ -176,15 +176,7 @@ function add_pyfixedformatter(cbar, vals::AVec)
...
-    end
+    PyPlot.LaTeXStrings.latexstring ∘ labelfunc_tex(scale)
```
Comment (isentropic) [inline src/backends/pyplot.jl:179]: I do not really understand this `\dot` operator, bu I assume it runs latexstring once again to cover the previous else statement

Comment (isentropic) [reply src/backends/pyplot.jl:179]: I just wanna make sure that https://github.com/JuliaPlots/Plots.jl/pull/2858 does not break because of this

File: src/axes.jl [hunk 4]
```diff
@@ -123,6 +123,14 @@ const _label_func = Dict{Symbol,Function}(
 )
 labelfunc(scale::Symbol, backend::AbstractBackend) = get(_label_func, scale, string)
 
+const _label_func_tex = Dict{Symbol,Function}(
+    :log10 => x -> "10^{$x}",
+    :log2 => x -> "2^{$x}",
+    :ln => x -> "e^{$x}",
+)
+labelfunc_tex(scale::Symbol) = get(_label_func_tex, scale, convert_sci_unicode)
```
Comment (isentropic) [inline src/axes.jl:131]: Good change I think

**Comment by BeastyBlacksmith** [comment]
> What needs to be done to trigger SnoopCompile on this branch?

You'd need to rebase on master

File: src/backends/pyplot.jl (hunk 3 above)
Comment (yha) [reply src/backends/pyplot.jl:179]: That's a `\circ` (function composition), not a `\dot`. It should behave identically to the original function. I just factored out the part that's shared between backends to `labelfunc_tex`.
I confirmed now that plots with "serif" on pyplot are also unchanged by this PR.

File: src/backends/pyplot.jl (hunk 2 above)
Comment (yha) [reply src/backends/pyplot.jl:186]: It's triggered as the default value in `labelfunc_tex`

**Comment by yha** [comment]
Rebased

**Comment by yha** [comment]
Seems like the SnoopCompile script needs updating? https://github.com/yha/Plots.jl/runs/975918743

**Comment by BeastyBlacksmith** [comment]
Hmm.. I see this error on master too, @aminya did anything change for the snoopcompile bot?

**Comment by aminya** [comment]
I think so. SnoopCompileBot is in a separate repository now because of the issues of the monorepo. I am trying to make it work again on my account.

I think @timholy has registered SnoopCompile which does not include SnoopCompileBot anymore.

**Comment by aminya** [comment]
> > It correctly updates the precompiles. Merge it to this branch: [yha#7](https://github.com/yha/Plots.jl/pull/7)
> 
> What did you change to make the precompiles work?

Nothing much 🤷‍♂️ I just removed the old precompile files and ran the CI again.

**Comment by yha** [comment]
This PR now requires updating most of the reference images, since the change of dashes to minus signs causes failures in the image comparison tests. I only have easy access to Windows machines, but it's probably better to generate the images on linux, since that's where it's run in CI.
I tested locally without the dash-to-minus change and tests pass.

**Comment by daschw** [comment]
I can update the reference images.

**Comment by daschw** [comment]
Looks good, still requires resolving of some conflicts.
