### PR TITLE
[RecipesBase] Use interpolation instead of qualification to drop dependance on the namespace of RecipesBase users

### LINKED ISSUE #4557: [BUG] `using RecipesBase: @recipe` is broken
The output of `@recipe` assumes that `RecipesBase` is loaded. This makes `using RecipesBase: @recipe` not work. Ideally, it should work, failing that, documenting the limitation would be nice.

### PR DESCRIPTION
**Pull request by LilithHafner**
We can't assume that folks will have RecipesBase in their namespace.

Fixes #4557

### CODE REVIEW

**Comment by LilithHafner** [comment]
CI is already failing after just a few minutes <3

**Comment by BeastyBlacksmith** [comment]
We can't expecpt them to have all those internal functions in the namespace either, I'd say.
The proper fix would be to document that users should at least use
```julia
using ReciperBase: RecipesBase, @recipe
```

**Comment by t-bltg** [comment]
As Simon suggested, improving the docs is probably the easiest.

With a [minor nitpick](https://github.com/JuliaLang/julia/issues/39235):
```julia
import RecipesBase: RecipesBase, @recipe
```

File: RecipesBase/test/runtests.jl [hunk 1]
```diff
@@ -1,47 +1,47 @@
-# Run tests with `import RecipesBase` instead of `using RecipesBase` to test
-# that objects like `AbstractPlot` are properly prefixed with `RecipesBase.` in
-# the macros.
-import RecipesBase
+# Run tests with `import RecipesBase as RB` instead of `using RecipesBase`
+# or `import RecipesBase` to test that macros do not depend on the
+# namespace of the emeclosing scope.
```
Comment (BeastyBlacksmith) [inline RecipesBase/test/runtests.jl:3]: Isn't the issue that `import RecipesBase` still imports the `RecipesBase` namespace while `using RecipesBase: @recipe` does not?

**Comment by LilithHafner** [comment]
The original approach (fb77991) should work if https://github.com/JuliaLang/julia/issues/47726 is fixed upstream.

**Comment by LilithHafner** [comment]
Failing that, a slightly more verbose approach should work following this pattern
```julia
julia> module NanoRecipesBase
           function apply_recipe end
           macro recipe(x)
               quote
                   let M = $NanoRecipesBase
                       M.apply_recipe() = $x
                   end
               end
           end
       end
Main.NanoRecipesBase

julia> module User
           import Main.NanoRecipesBase: @recipe
           try
               println(NanoRecipesBase)
           catch UndefVarError
               println("Good")
           end
           @recipe 1729
       end
Good
Main.User

julia> NanoRecipesBase.apply_recipe()
1729
```

File: RecipesBase/test/runtests.jl (hunk 1 above)
Comment (LilithHafner) [reply RecipesBase/test/runtests.jl:3]: We could use `import RecipesBase: @recipe` in testing, but that would add `@recipe` to the namespace. This adds only `RB` which is an abbreviation that is not even used in the source code (afaik)

**Comment by LilithHafner** [comment]
> The proper fix would be to document that users should at least use

> As Simon suggested, improving the docs is probably the easiest.

We should only document an unexpected limitation/bug if we can't fix it. This PR should fix it :)

**Comment by LilithHafner** [comment]
The format check gave a lot of diffs. Is there a way to avoid transcribing all those non-functional-changes manually?

**Comment by t-bltg** [comment]
https://docs.juliaplots.org/latest/contributing/#Write-code,-and-format

**Review by t-bltg — APPROVED** [review]
Nice.

File: RecipesBase/src/RecipesBase.jl [hunk 2]
```diff
@@ -332,18 +330,13 @@ end
...
-            end
-        end,
-    )
+    esc(quote
+        let plotattributes = copy(plotattributes)
+            args = $expr
+            push!(series_list, $RecipeData(plotattributes, $wrap_tuple(args)))
+            nothing
+        end
+    end)
```
Comment (t-bltg) [inline RecipesBase/src/RecipesBase.jl:339]:
```suggestion
    quote
        let plotattributes = copy(plotattributes)
            args = $expr
            push!(series_list, $RecipeData(plotattributes, $wrap_tuple(args)))
            nothing
        end
    end |> esc
```

Minor stylistic enhancement.

**Comment by t-bltg** [comment]
Seems like using `GlobalRef` triggers a segfault apocalypse here :laughing:

**Comment by LilithHafner** [comment]
Strange. I guess I'll just revert to 5440348 "fix formatting".

**Comment by LilithHafner** [comment]
I don't understand the `GlobalRef` segfaults so I asked on Discourse: https://discourse.julialang.org/t/what-is-a-globalref-and-how-i-use-it/90971

**Comment by LilithHafner** [comment]
Thanks [@ffevotte](https://discourse.julialang.org/u/ffevotte) from discourse for the latest and best workaround for julia#47726

**Comment by t-bltg** [comment]
Looks good, thanks for getting to the bottom of this with a cleaner solution. Still intrigued by the `GlobalRef` segfault though :thinking:

File: RecipesBase/test/runtests.jl (hunk 1 above)
Comment (BeastyBlacksmith) [inline RecipesBase/test/runtests.jl:3]:
```suggestion
# namespace of the enclosing scope.
```

**Review by BeastyBlacksmith — APPROVED** [review]

File: RecipesBase/src/RecipesBase.jl [hunk 3]
```diff
@@ -123,7 +123,7 @@ function create_kw_body(func_signature::Expr)
             push!(
                 cleanup_body.args,
                 :(
-                    RecipesBase.is_key_supported($(QuoteNode(k))) ||
+                    $is_key_supported($(QuoteNode(k))) ||
```
[the remark this answers is not in the document]
Comment (LilithHafner) [reply RecipesBase/src/RecipesBase.jl]: Because there is no need to interpolate the module at method _calls_. interpolating the function directly is more straightforward and clear than interpolating the module and then looking up the function within the module.

**Comment by LilithHafner** [comment]
I'm happy with [de5a423](https://github.com/JuliaPlots/Plots.jl/pull/4559/commits/de5a423e7a5911fdca2fdae117c4f2db80539b29), but I believe [e9e12d6](https://github.com/JuliaPlots/Plots.jl/pull/4559/commits/e9e12d6a5a69c55a8c4eee486d7b0980ea7a4b38) contains unnecessarily indirect interpolation.

File: RecipesBase/src/RecipesBase.jl (hunk 3 above)
[the remark this answers is not in the document]
Comment (t-bltg) [reply RecipesBase/src/RecipesBase.jl]: This is inconsistent with https://github.com/LilithHafner/Plots.jl/blob/patch-1/RecipesBase/src/RecipesBase.jl#L90 then.

File: RecipesBase/src/RecipesBase.jl [hunk 4]
```diff
@@ -87,7 +87,7 @@ function get_function_def(func_signature::Expr, args::Vector)
     elseif func_signature.head ≡ :call
         func = Expr(
             :call,
-            :(RecipesBase.apply_recipe),
+            :($RecipesBase.apply_recipe),
```
Comment (t-bltg) [inline RecipesBase/src/RecipesBase.jl:90]:
```suggestion
            :($apply_recipe),
```

We tries that, but it failed, right ?

Comment (LilithHafner) [reply RecipesBase/src/RecipesBase.jl:90]: Yes. This is a definition, so we need indirect interpolation because of JuliaLang/julia#47726.
In all other cases the more direct approach works (note that all tests pass on [de5a423](https://github.com/JuliaPlots/Plots.jl/pull/4559/commits/de5a423e7a5911fdca2fdae117c4f2db80539b29))

Comment (t-bltg) [reply RecipesBase/src/RecipesBase.jl:90]: In this case, and because this is a low-level julia detail (maybe bug, I'm not competent to say it is), I would prefer to be explicit and consistent, instead of being implicit and kindof obscure.
IMO, it is not immediately obvious to the reader of `RecipesBase` code why you can use `:($is_key_supported)` in some place and not `:($apply_recipe)`.

**Comment by LilithHafner** [comment]
> Do you implicit that those added interpolations have a runtime performance penalty ?

No. There should not be a runtime penalty.

**Comment by LilithHafner** [comment]
Ultimately, it's just a style/formatting choice. I prefer direct interpolation over module interpolation + qualified reference because it is shorter, but either should work, and y'all are more likely to be maintaining this than me so feel free to pick whatever style you prefer.

**Comment by t-bltg** [comment]
We disagree on this one, and I explained my position in https://github.com/JuliaPlots/Plots.jl/pull/4559#discussion_r1035672905.

Thanks for the contribution and the detailed analysis here !

File: RecipesBase/src/RecipesBase.jl (hunk 4 above)
Comment (t-bltg) [reply RecipesBase/src/RecipesBase.jl:90]: Side note: [Explicit is better than implicit](https://peps.python.org/pep-0020/#the-zen-of-python), taking the good bits from `Python` ...
