### PR TITLE
Title location and alignment

### LINKED ISSUE #4407: [BUG] Plot title location is ignored
## Details
Specifying location of plot title with `titleloc` fails on some backends

```julia
using Plots
test() = plot(plot([0,1],[0,1]; title="title", titleloc=:left),
              plot([0,1],[0,1]; title="title", titleloc=(0,1)))

gr()
test() # :left works, (0,1) does not

inspectdr()
test() # does not work

pgfplotsx()
test() # all OK

unicodeplots()
test() # does not work

plotly()
test() # :left works, (0,1) does not
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly     |  x   |     | 
plotlyjs     |     |     | x
pgfplotsx    |     |  x   |
unicodeplots |  x   |     |
inspectdr    |  x   |     |
gaston       |     |     | x

### Versions

Plots.jl version: 1.35.0
Backend  version (`]st -m <backend(s)>`):
```
InspectDR v.0.4.3
PGFPlotsX v.1.5.1
Plotly v.0.4.1
UnicodePlots v.3.1.3
```
Output of `versioninfo()`:
```
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_DEPOT_PATH = /home/ivan/.local/share/julia:/home/ivan/.local/share/julia:
```

### PR DESCRIPTION
**Pull request by ivan-boikov**
Adds manual plot title positioning with a tuple (x,y) (as was done in PGFPlotsX) for GR and Plotly.
Also adds title font alignment for GR, Plotly and PGFPlotsX since it also impacts title position. 

Problems:
-  PGFPlotsX  puts title _center_ at given coordinates and then aligns, while GR and Plotly align entire title relative to given coordinates. I am not sure what's the expected behaviour, so I left as it was.
- UnicodePlots does not allow control over title location 
- InspectDR only supports offset in vertical direction, moreover plot area is painted over title, so title cannot be placed inside plot as in GR, Plotly and PGFPlotsX

Partially fixes #4407 (since only GR and Plotly are fixed).

### CODE REVIEW

File: src/backends/gr.jl [hunk 1]
```diff
@@ -1814,17 +1814,36 @@ function gr_add_title(sp, viewport_plotarea, viewport_subplot)
...
+            elseif halign == :right
+                halign = GR.TEXT_HALIGN_RIGHT
+            end
+            if valign == :top
+                valign = GR.TEXT_VALIGN_TOP
+            elseif valign == :vcenter || valign == :center
+                valign = GR.TEXT_VALIGN_HALF
+            elseif valign == :bottom
+                valign = GR.TEXT_VALIGN_BOTTOM
+            end
```
Comment (t-bltg) [inline src/backends/gr.jl:1843]:
```suggestion
            halign = gr_halign(sp[:titlefonthalign])
            valign = gr_valign(sp[:titlefontvalign])
```

If think the helpers `gr_halign` and `gr_valign` defined in this file will work no ?

Comment (ivan-boikov) [reply src/backends/gr.jl]: Yeah, good call, thanks

**Review by t-bltg — APPROVED** [review]
It is difficult to test this without ref images (since it is backend dependent), and I don't think adding some is necessary, so LGTM.

> Problems:

This is already an improvement over the current state: it is left for another PR.
